//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITU
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTransparencia
    {
        public CatalogoTransparencia()
        {
            this.MapeosReportes = new HashSet<MapeosReportes>();
        }
    
        public System.Guid CT_NodoId { get; set; }
        public Nullable<System.Guid> CT_NodoPadreId { get; set; }
        public string CT_Descripcion { get; set; }
        public string CT_Texto { get; set; }
        public Nullable<System.Guid> CT_CMTR_TipoRangoId { get; set; }
        public Nullable<int> CT_Rango { get; set; }
        public bool CT_Activo { get; set; }
        public int CT_Orden { get; set; }
        public Nullable<System.DateTime> CT_FechaUltimaModifacion { get; set; }
        public Nullable<System.Guid> CT_USU_ModificaPorId { get; set; }
        public byte[] CT_Timestamp { get; set; }
    
        public virtual ControlesMaestrosTiposRangos ControlesMaestrosTiposRangos { get; set; }
        public virtual ICollection<MapeosReportes> MapeosReportes { get; set; }
    }
}
