//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITU
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoTransparenciaReportes
    {
        public System.Guid CTR_ReporteId { get; set; }
        public System.Guid CTR_MR_MapeoId { get; set; }
        public string CTR_NombreArchivo { get; set; }
        public string CTR_DescripcionArchivo { get; set; }
        public Nullable<System.DateTime> CTR_FechaInicio { get; set; }
        public System.DateTime CTR_FechaFin { get; set; }
        public bool CTR_Visible { get; set; }
        public bool CTR_Borrado { get; set; }
        public System.DateTime CTR_FechaRegistro { get; set; }
        public System.Guid CTR_USU_SubidoPorId { get; set; }
        public System.DateTime CTR_FechaUltimaModificacion { get; set; }
        public System.Guid CTR_USU_ModificadoPorId { get; set; }
        public byte[] CTR_Timestamp { get; set; }
    
        public virtual MapeosReportes MapeosReportes { get; set; }
    }
}
