//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITU
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlesMaestrosTiposRangos
    {
        public ControlesMaestrosTiposRangos()
        {
            this.CatalogoTransparencia = new HashSet<CatalogoTransparencia>();
        }
    
        public System.Guid CMTR_TipoRangoId { get; set; }
        public string CMTR_TipoRango { get; set; }
        public byte[] CMTR_Timestamp { get; set; }
    
        public virtual ICollection<CatalogoTransparencia> CatalogoTransparencia { get; set; }
    }
}
