//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITU
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapeosReportes
    {
        public MapeosReportes()
        {
            this.CatalogoTransparenciaReportes = new HashSet<CatalogoTransparenciaReportes>();
        }
    
        public System.Guid MR_MapeoId { get; set; }
        public string MR_RutaFisicaReporte { get; set; }
        public System.Guid MR_CT_NodoId { get; set; }
        public string MR_Acronimo { get; set; }
        public byte[] MR_Timestamp { get; set; }
    
        public virtual CatalogoTransparencia CatalogoTransparencia { get; set; }
        public virtual ICollection<CatalogoTransparenciaReportes> CatalogoTransparenciaReportes { get; set; }
    }
}
