//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public System.Guid USU_UsuarioId { get; set; }
        public string USU_NombreUsuario { get; set; }
        public string USU_CorreoElectronico { get; set; }
        public string USU_Contrasenia { get; set; }
        public bool USU_Activo { get; set; }
        public System.Guid USU_RegistradoPor { get; set; }
        public System.DateTime USU_FechaRegistro { get; set; }
        public byte[] USU_Timestamp { get; set; }
    }
}
